name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install, build, and upload your site
        run: npx vite build

      - name: check
        run: ls -la ./dist
  
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages 
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Allow GitHub Actions to deploy to Pages
      id-token: write
      
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist
      # Step 6: Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
